# Generated by Django 3.1.dev20191024131625 on 2019-10-25 02:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('price_tier', models.CharField(max_length=4)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(verbose_name='date created')),
                ('location', models.CharField(max_length=50)),
                ('favorite_restaurant', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(max_length=20)),
                ('dietary_restrictions', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(10)])),
                ('restuarant_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_open', models.CharField(max_length=8)),
                ('m_close', models.CharField(max_length=8)),
                ('t_open', models.CharField(max_length=8)),
                ('t_close', models.CharField(max_length=8)),
                ('w_open', models.CharField(max_length=8)),
                ('w_close', models.CharField(max_length=8)),
                ('th_open', models.CharField(max_length=8)),
                ('th_close', models.CharField(max_length=8)),
                ('f_open', models.CharField(max_length=8)),
                ('f_close', models.CharField(max_length=8)),
                ('sa_open', models.CharField(max_length=8)),
                ('sa_close', models.CharField(max_length=8)),
                ('su_open', models.CharField(max_length=8)),
                ('su_close', models.CharField(max_length=8)),
                ('restuarant_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Restaurant')),
            ],
        ),
    ]
