# Generated by Django 2.2.6 on 2019-10-24 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='restuarant_name',
            new_name='restaurant_name',
        ),
    ]
