# Generated by Django 2.2.6 on 2019-12-03 03:41

from django.db import migrations, models
import djongo.models.fields
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant_Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('avg_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('review_list', djongo.models.fields.ArrayModelField(model_container=polls.models.Reviews, model_form_class=polls.models.ReviewForm)),
                ('tag_list', djongo.models.fields.ArrayModelField(model_container=polls.models.Cuisine_Tags, model_form_class=polls.models.CuisineForm)),
            ],
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
