# Generated by Django 2.2.6 on 2019-12-04 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20191202_2141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restaurant_Reviews',
        ),
    ]
