# Generated by Django 2.2.6 on 2019-12-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20191201_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='user_name',
            field=models.CharField(max_length=50),
        ),
    ]
