# Generated by Django 2.2.6 on 2019-12-02 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20191130_1609'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
