# Generated by Django 2.2.6 on 2019-12-02 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20191201_2126'),
        ('polls', '0005_auto_20191201_2215'),
    ]

    operations = [
    ]
