# Generated by Django 2.2.6 on 2019-12-02 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_reviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
