# Generated by Django 2.2.6 on 2019-12-02 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_merge_20191201_2257'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
